version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.9.0
  cloudrun: circleci/gcp-cloud-run@1.0.2
jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - run:
          name: Run Tests
          command: |
            yarn test
  build_push_image_cloud_run_mangaged:
    docker:
      # can swap back to cimg/base:2020.01 when the cloud run orb is fixed
      - image: google/cloud-sdk:314.0.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 19.03.13 # because of https://support.circleci.com/hc/en-us/articles/360050934711
      - run:
          name: Build Docker image
          command: |
            echo ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
            echo 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/gcloud-service-key.json)' >> $BASH_ENV
            echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
            echo 'export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV
            source $BASH_ENV
            env \
              IMAGE_PREFIX=gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME \
              IMAGE_TAG=$TAG \
              bash docker-build.sh
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: "gcr.io"
          image: $IMAGE_NAME
      - run:
          name: Prepare runtime env var param
          # this is split into its own command so we can leverage YAML multiline
          # strings to make it readable.
          command: "echo export SET_ENV_PARAM=\"\
            --set-env-vars \
                INAT_API_PREFIX=$INAT_API_PREFIX,\
                INAT_PREFIX=$INAT_PREFIX,\
                INAT_PROJECT_SLUG=$INAT_PROJECT_SLUG,\
                OAUTH_APP_ID=$OAUTH_APP_ID,\
                OAUTH_APP_SECRET=$OAUTH_APP_SECRET,\
                OAUTH_USERNAME=$OAUTH_USERNAME,\
                OAUTH_PASSWORD=$OAUTH_PASSWORD,\
                SENTRY_DSN=$SENTRY_DSN,\
                CLIENT1_API_KEY=$CLIENT1_API_KEY,\
                CLIENT2_API_KEY=$CLIENT2_API_KEY,\
                CLIENT3_API_KEY=$CLIENT3_API_KEY,\
                CLIENT4_API_KEY=$CLIENT4_API_KEY\" \
                >> $BASH_ENV"
      - run:
        # the CircleCI orb won't let us pass args until this is fixed
        # https://github.com/CircleCI-Public/gcp-cloud-run-orb/issues/5
        # so we'll just do it ourselves.
          name: Deploy to Cloud Run
          command: |
            source $BASH_ENV
            GCP_PLATFORM=managed
            GCP_SERVICE_NAME=wow-api-facade
            gcloud beta run deploy $GCP_SERVICE_NAME \
            --image gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME \
            --region $GOOGLE_COMPUTE_ZONE \
            --allow-unauthenticated \
            --platform $GCP_PLATFORM \
            $SET_ENV_PARAM
            echo
            echo "Service deployed"
            echo
            GET_GCP_DEPLOY_ENDPOINT=$(gcloud beta run services describe $GCP_SERVICE_NAME --platform $GCP_PLATFORM --region $GOOGLE_COMPUTE_ZONE --format="value(status.address.url)")
            echo "export GCP_DEPLOY_ENDPOINT=$GET_GCP_DEPLOY_ENDPOINT" >> $BASH_ENV
            source $BASH_ENV
            echo $GCP_DEPLOY_ENDPOINT
workflows:
  build_test_deploy:
    jobs:
      - build_test
      - build_push_image_cloud_run_mangaged:
          requires:
            - build_test
