version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.9.0
  cloudrun: circleci/gcp-cloud-run@1.0.2
jobs:
  do_tests:
    docker:
      - image: circleci/node:14
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - run:
          name: Lint code
          command: |
            yarn lint
      - run:
          name: Run Tests
          command: |
            yarn test
  build_push_image:
    docker:
      - image: google/cloud-sdk:381.0.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 19.03.13 # because of https://support.circleci.com/hc/en-us/articles/360050934711
      - run:
          name: Build Docker image
          command: |
            # IMAGE_NAME and IMAGE_TAG come from here
            source .circleci/config-env.sh
            ./.docker-cmd-helper build_circleci
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - run:
          name: Push image to GCR
          command: |
            # print as base64 to side-step secret obfuscation; for debugging
            echo $IMAGE_FULL | base64 -w0; echo ''
            docker push $IMAGE_FULL
  deploy_master:
    docker:
      - image: google/cloud-sdk:381.0.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: Deploy to Cloud Run (master)
          command: |
            source .circleci/config-env.sh
            export GCP_SERVICE_NAME=wow-api-facade
            export CUSTOM_DOMAIN=api-facade.wildorchidwatch.org
            export GCP_SECRET_PREFIX=PROD_
            export DEPLOYED_ENV_NAME=production
            bash .circleci/deploy-cloud-run.sh
  deploy_dev:
    docker:
      - image: google/cloud-sdk:381.0.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: Deploy to Cloud Run (dev)
          command: |
            source .circleci/config-env.sh
            export GCP_SERVICE_NAME=dev-wow-api-facade
            export CUSTOM_DOMAIN=dev-api-facade.wildorchidwatch.org
            export GCP_SECRET_PREFIX=DEV_
            export DEPLOYED_ENV_NAME=development
            bash .circleci/deploy-cloud-run.sh
workflows:
  dev:
    jobs:
      - do_tests
      - build_push_image:
          filters:
            branches:
              only: dev
          requires:
            - do_tests
      - deploy_dev:
          requires:
            - build_push_image
  prod:
    jobs:
      - do_tests:
          filters:
            branches:
              only: master
      - build_push_image:
          requires:
            - do_tests
      - deploy_master:
          requires:
            - build_push_image
